@startuml class-diagram
  class Option {
    +value : string
    +__construct(key)
    +get()
  }
  class Settings {
    {static} +admin_init()
    {static} +render_section(args)
    {static} +render_fields(args)
    {static} +sanitize_text_field(fields)
  }
  class Plugin {
    -file : string
    {static} +init(file)
    +__construct(file)
    +plugins_loaded()
    {static} +wp_dashboard_setup()
    +widgets_init()
    +block_init()
    {static} +block_render()
    +plugins_url(path)
    +dirname(path)
    +path()
    +url()
  }
  class AdminWidget {
    #status : ApiStatus
    +__construct(status)
    {static} +create(status)
    +render()
  }
  class OptionsPage {
    {static} +admin_menu()
    {static} +render_page()
    {static} +add_settings_error(arr)
  }
  class Widget {
    +__construct()
    +widget(args, instance)
    +update(new_instance, old_instance)
    +form(instance)
  }
  package Integration as Integration <<Rectangle>> {
    class Integration.ApiStatus {
      +get()
    }
    class Integration.Payment {
      +set(price_amount, price_currency, pay_currency, optional_params)
      +post()
    }
    class Integration.MinimumPaymentAmount {
      +set(currency_from, currency_to)
      +get()
    }
    class Integration.AvailableCurrencies {
      +get()
      +is_available(currency)
    }
    class Integration.EstimatedPrice {
      +set(amount, currency_from, currency_to)
      +get()
    }
    class Integration.PaymentStatus {
      +set(payment_id)
      +get()
    }
  }
  package Logs as Logs <<Rectangle>> {
    class Logs.ApplicationLogs {
      #logger : Logger
      +__construct(logger)
      {static} +init(logger)
      +http_api_debug(response, context, class, parsed_args, url)
    }
    class Logs.LogFactory {
      {static} +get_logger()
    }
    class Logs.StructuredLogsFormatter {
      +format(record)
    }
  }
  package Rest as Rest <<Rectangle>> {
    interface Rest.Result {
      +get()
    }
    class Rest.Error {
      #error : WP_Error
      +__construct(error)
      +get()
    }
    class Rest.Service {
      -environment : string
      +__construct(environment)
      {static} +create()
      +get_service_url()
      +get(method)
      +info()
    }
    class Rest.Client {
      -service : Service
      +__construct(service)
      +get_service()
      +get(endpoint, body, headers)
      +post(endpoint, body, headers)
    }
    class Rest.Response {
      #response : string[]
      +__construct(response)
      +get()
    }
    class Rest.Endpoint {
      #client : Client
      -header : string[]
      -body : string[]
      +__construct(client)
      +get_client()
      #get_headers()
      #set_header(params)
      #get_body()
      #set_body(params)
      +__call(name, arguments)
    }
  }
  AdminWidget ..> Integration.ApiStatus
  Plugin ..> AdminWidget
  Rest.Client ..> Rest.Service
  Rest.Client ..> Rest.Service
  Rest.Endpoint ..> Rest.Client
  Rest.Endpoint ..> Rest.Client
  Rest.Endpoint <|-- Integration.ApiStatus
  Rest.Endpoint <|-- Integration.AvailableCurrencies
  Rest.Endpoint <|-- Integration.EstimatedPrice
  Rest.Endpoint <|-- Integration.MinimumPaymentAmount
  Rest.Endpoint <|-- Integration.Payment
  Rest.Endpoint <|-- Integration.PaymentStatus
  Rest.Result <|-- Rest.Error
  Rest.Result <|-- Rest.Response
  Rest.Service ..> Rest.Service
@enduml
